name: pr-test
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: TAG=testing make test-all
